language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.1
matrix:
  include:
  - otp_release: 19.3
    elixir: 1.7.1
env:
  global:
    - MIX_ENV=test
script:
  - mix format --check-formatted
  - mix credo --strict
  - mix dialyzer --halt-exit-status
  - mix test